/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ../public/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({...props}) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={54351.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
      <PerspectiveCamera name="Camera" makeDefault={true} far={-1000} near={0.1} fov={22.9} position={[7.359, 4.958, 6.926]} rotation={[2.94, -0.78, 3]} />
      <mesh geometry={nodes['f22a-airframe'].geometry} material={materials['f22a-airframe']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-canopy'].geometry} material={materials['f22a-canopy']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-cockpit'].geometry} material={materials['f22a-cockpit']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-hud'].geometry} material={materials['f22a-hud']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-instrGlass'].geometry} material={materials['f22a-canopy']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-landingOff'].geometry} material={materials['f22a-airframe']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-landingOn'].geometry} material={materials['f22a-airframe']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-landingOnLight'].geometry} material={materials['f22a-landingLights']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-refuelOff'].geometry} material={materials['f22a-airframe']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-spw1-spw2-qaam-xsdb-rail_f22a-spw1-qaam-rail'].geometry} material={materials['f22a-airframe']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['f22a-spw3-8aam-rail'].geometry} material={materials['f22a-airframe']} position={[0, 0, 2.411]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/model.glb')
